name: build-and-deploy-production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-acr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login into Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: gmtpostechacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t techchallengetwoapp:${{ github.sha }} .

    - name: Tag Docker Image
      run: docker tag techchallengetwoapp:${{ github.sha }} gmtpostechacr.azurecr.io/techchallengetwoapp:${{ github.sha }}

    - name: Push Docker to Azure Container Registry
      run: docker push gmtpostechacr.azurecr.io/techchallengetwoapp:${{ github.sha }}

  push-to-aci:
    needs: build-and-push-acr
    runs-on: ubuntu-latest

    steps:
    - name: Login into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
          resource-group: gmtpostechrg
          name: gmtpostechaci
          image: gmtpostechacr.azurecr.io/techchallengetwoapp:${{ github.sha }}
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
          dns-name-label: gmtpostechrg${{ github.run_number }}
          location: 'brazilsouth'